#pragma once

namespace Corium3D {
	enum KeyboardInputID {
		A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
		a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z,
		NUMROW0, NUMROW1, NUMROW2, NUMROW3, NUMROW4, NUMROW5, NUMROW6, NUMROW7, NUMROW8, NUMROW9,
		NUMPAD0, NUMPAD1, NUMPAD2, NUMPAD3, NUMPAD4, NUMPAD5, NUMPAD6, NUMPAD7, NUMPAD8, NUMPAD9,
		LEFT_CURLY_BRACKET, RIGHT_CURLY_BRACKET, LEFT_SQR_BRACKET, RIGHT_CURLY_BRACKER,
		LEFT_PARENTHESES, RIGHT_PARENTHESES, LEFT_TRIANGLE_BRACKT, RIGHT_TRIANGLE_BRACKET,
		SEMI_COLON, COLON, PERIOD, COMMA, QUOTE, DOUBLE_QUOTES, APOSTROPHE, BACK_QUOTE, SLASH, BACK_SLASH,
		QUESTION_MARK, EXCLAMATION_MARK, AT_MARK, HASHTAG, DOLLAR_SIGN, PERCENT_MARK, CARET, AMPERSAND, STAR,
		MINUS_SIGN, UNDERSCORE_SIGN, PLUS_SIGN, EQUALS_SIGN, TILDE, VERTICAL_BAR,
		ESC, LEFT_SHIFT, RIGHT_SHIFT, LEFT_CTRL, RIGHT_CTRL, LEFT_ALT, RIGHT_ALT, CAPS_LOCK, SCROLL_LOCK, NUM_LOCK, PRINT_SCREEN,
		SPACE, ENTER, BACKSPACE, DEL, INSERT, TAB, HOME, END, PAGEUP, PAGEDOWN, LEFT_ARROW, RIGHT_ARROW, UP_ARROW, DOWN_ARROW,
		F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, __KEYBOARD_INPUT_IDS_NR__
	};

	enum CursorInputID {
		LEFT_DOWN, LEFT_UP, RIGHT_DOWN, RIGHT_UP, MIDDLE_DOWN, MIDDLE_UP, WHEEL_ROTATED_FORWARD, WHEEL_ROTATED_BACKWARD, MOVE, __CURSOR_INPUT_IDS_NR__
	};
}